import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "@/components/provider/theme-provider";
import "./globals.css";
import { NotificationProvider } from "@/hooks/use-notifikasi";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.className} antialiased`}>
				<NotificationProvider>
					<Toaster />
					<ThemeProvider
						attribute="class"
						defaultTheme="light"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</NotificationProvider>
			</body>
		</html>
	);
}

